nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.1.cjs
packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "firebase@*":
    dependencies:
      "@firebase/auth": "*"
      "@firebase/app": "*"
  "@splitrack@*":
    dependencies:
      "@firebase/auth": "*"
      "@firebase/app": "*"