apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ravenCertSecretName" . }}
data:
  keystore.p12: {{ required "raven.certificateBase64 missing" .Values.raven.certificateBase64 }}
stringData:
  password: "{{ required "raven.certificatePassword missing" .Values.raven.certificatePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidcSecretName" . }}
stringData:
  client-secret: "{{ required "sso.oidcClientSecret missing" .Values.sso.oidcClientSecret }}"
  